### ISSUE TITLE
MemoryError: ('cairo returned CAIRO_STATUS_NO_MEMORY: out of memory', 1) when rendering to PNG

### ISSUE THREAD

**Issue by sergani** [Kozea/CairoSVG#122]
Hello,

I have a strange situation where rendering from SVG to PNG always raises:

``` python
Traceback (most recent call last):
  File "/usr/bin/cairosvg", line 25, in <module>
    cairosvg.main()
  File "/usr/lib/python2.6/site-packages/cairosvg/__init__.py", line 104, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 108, in convert
    cls(tree, output, dpi, None, parent_width, parent_height).finish()
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 161, in __init__
    self.draw_root(tree)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 433, in draw_root
    self.draw(node)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/__init__.py", line 328, in draw
    TAGS[node.tag](self, node)
  File "/usr/lib/python2.6/site-packages/cairosvg/surface/text.py", line 90, in text
    surface.context.font_extents())
  File "/usr/lib/python2.6/site-packages/cairocffi/context.py", line 1929, in font_extents
    self._check_status()
  File "/usr/lib/python2.6/site-packages/cairocffi/context.py", line 108, in _check_status
    _check_status(cairo.cairo_status(self._pointer))
  File "/usr/lib/python2.6/site-packages/cairocffi/__init__.py", line 74, in _check_status
    raise exception(message, status)
MemoryError: ('cairo returned CAIRO_STATUS_NO_MEMORY: out of memory', 1)
```

I initially faced this issue when using pygal 2.2 and 2.3 under python2.7:

``` python
Traceback (most recent call last):
  File "./performance_reports.py", line 695, in <module>
    payments_graph.render_to_png('/home/test/graphs/payments.png')
  File "/usr/local/lib/python2.7/site-packages/pygal/graph/public.py", line 120, in render_to_png
    bytestring=self.render(**kwargs), write_to=filename, dpi=dpi)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/__init__.py", line 43, in <lambda>
    surface_type.convert(*args, **kwargs))(_surface_type)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 108, in convert
    cls(tree, output, dpi, None, parent_width, parent_height).finish()
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 161, in __init__
    self.draw_root(tree)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 214, in draw_root
    self.draw(node)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 328, in draw
    TAGS[node.tag](self, node)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/text.py", line 90, in text
    surface.context.font_extents())
  File "/usr/local/lib/python2.7/site-packages/cairocffi/context.py", line 1929, in font_extents
    self._check_status()
  File "/usr/local/lib/python2.7/site-packages/cairocffi/context.py", line 108, in _check_status
    _check_status(cairo.cairo_status(self._pointer))
  File "/usr/local/lib/python2.7/site-packages/cairocffi/__init__.py", line 74, in _check_status
    raise exception(message, status)
MemoryError: ('cairo returned CAIRO_STATUS_NO_MEMORY: out of memory', 1)
```

The contents of the SVG are as follows:

``` xml
<?xml version='1.0' encoding='utf-8'?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="chart-fd6295b0-7bc2-4262-87f0-420fb645dbec" class="pygal-chart" viewBox="0 0 800 600"><!--Generated with pygal 2.3.0 (lxml) ©Kozea 2012-2016 on 2016-10-30--><!--http://pygal.org--><!--http://github.com/Kozea/pygal--><defs><style type="text/css">#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec{-webkit-user-select:none;-webkit-font-smoothing:antialiased;font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .title{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:16px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .legends .legend text{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:14px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis text{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:10px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis text.major{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:10px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .text-overlay text.value{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:16px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .text-overlay text.label{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:10px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:14px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec text.no_data{font-family:Consolas,"Liberation Mono",Menlo,Courier,monospace;font-size:64px}
#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec{background-color:rgba(249,249,249,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec path,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec rect,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec circle{-webkit-transition:150ms;-moz-transition:150ms;transition:150ms}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .graph &gt; .background{fill:rgba(249,249,249,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .plot &gt; .background{fill:rgba(255,255,255,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .graph{fill:rgba(0,0,0,.87)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec text.no_data{fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .title{fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .legends .legend text{fill:rgba(0,0,0,.87)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .legends .legend:hover text{fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .line{stroke:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .guide.line{stroke:rgba(0,0,0,.54)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .major.line{stroke:rgba(0,0,0,.87)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis text.major{fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y .guides:hover .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .line-graph .axis.x .guides:hover .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .stackedline-graph .axis.x .guides:hover .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .xy-graph .axis.x .guides:hover .guide.line{stroke:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .guides:hover text{fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .reactive{fill-opacity:.7;stroke-opacity:.8}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .ci{stroke:rgba(0,0,0,.87)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .reactive.active,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .active .reactive{fill-opacity:.8;stroke-opacity:.9;stroke-width:4}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .ci .reactive.active{stroke-width:1.5}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .series text{fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip rect{fill:rgba(255,255,255,1);stroke:rgba(0,0,0,1);-webkit-transition:opacity 150ms;-moz-transition:opacity 150ms;transition:opacity 150ms}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip .label{fill:rgba(0,0,0,.87)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip .label{fill:rgba(0,0,0,.87)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip .legend{font-size:.8em;fill:rgba(0,0,0,.54)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip .x_label{font-size:.6em;fill:rgba(0,0,0,1)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip .xlink{font-size:.5em;text-decoration:underline}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip .value{font-size:1.5em}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .bound{font-size:.5em}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .max-value{font-size:.75em;fill:rgba(0,0,0,.54)}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .map-element{fill:rgba(255,255,255,1);stroke:rgba(0,0,0,.54) !important}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .map-element .reactive{fill-opacity:inherit;stroke-opacity:inherit}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .color-0,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .color-0 a:visited{stroke:#F44336;fill:#F44336}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .color-1,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .color-1 a:visited{stroke:#3F51B5;fill:#3F51B5}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .color-2,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .color-2 a:visited{stroke:#009688;fill:#009688}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .text-overlay .color-0 text{fill:black}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .text-overlay .color-1 text{fill:black}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .text-overlay .color-2 text{fill:black}
#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec text.no_data{text-anchor:middle}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .guide.line{fill:none}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .centered{text-anchor:middle}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .title{text-anchor:middle}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .legends .legend text{fill-opacity:1}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.x text{text-anchor:middle}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.x:not(.web) text[transform]{text-anchor:start}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.x:not(.web) text[transform].backwards{text-anchor:end}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y text{text-anchor:end}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y text[transform].backwards{text-anchor:start}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y2 text{text-anchor:start}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y2 text[transform].backwards{text-anchor:end}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .guide.line{stroke-dasharray:4,4}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .major.guide.line{stroke-dasharray:6,6}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .horizontal .axis.y .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .horizontal .axis.y2 .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .vertical .axis.x .guide.line{opacity:0}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .horizontal .axis.always_show .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .vertical .axis.always_show .guide.line{opacity:1 !important}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y .guides:hover .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.y2 .guides:hover .guide.line,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis.x .guides:hover .guide.line{opacity:1}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .axis .guides:hover text{opacity:1}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .nofill{fill:none}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .subtle-fill{fill-opacity:.2}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .dot{stroke-width:1px;fill-opacity:1}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .dot.active{stroke-width:5px}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .dot.negative{fill:transparent}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec text,#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec tspan{stroke:none !important}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .series text.active{opacity:1}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip rect{fill-opacity:.95;stroke-width:.5}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .tooltip text{fill-opacity:1}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .showable{visibility:hidden}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .showable.shown{visibility:visible}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .gauge-background{fill:rgba(229,229,229,1);stroke:none}#chart-fd6295b0-7bc2-4262-87f0-420fb645dbec .bg-lines{stroke:rgba(249,249,249,1);stroke-width:2px}</style><script type="text/javascript">window.pygal = window.pygal || {};window.pygal.config = window.pygal.config || {};window.pygal.config['fd6295b0-7bc2-4262-87f0-420fb645dbec'] = {"dynamic_print_values": false, "truncate_label": null, "inner_radius": 0, "print_values": true, "xrange": null, "box_mode": "extremes", "title": "Payments Per Gateway (in USD)", "legend_at_bottom_columns": null, "height": 600, "legend_at_bottom": false, "show_legend": true, "show_dots": true, "explicit_size": false, "y_labels_major": null, "show_minor_x_labels": true, "width": 800, "force_uri_protocol": "https", "half_pie": false, "style": {"major_label_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "title_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "stroke_opacity": ".8", "legend_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "colors": ["#F44336", "#3F51B5", "#009688", "#FFC107", "#FF5722", "#9C27B0", "#03A9F4", "#8BC34A", "#FF9800", "#E91E63", "#2196F3", "#4CAF50", "#FFEB3B", "#673AB7", "#00BCD4", "#CDDC39", "#9E9E9E", "#607D8B"], "legend_font_size": 14, "no_data_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "major_label_font_size": 10, "value_background": "rgba(229, 229, 229, 1)", "ci_colors": [], "label_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "label_font_size": 10, "tooltip_font_size": 14, "value_font_size": 16, "font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "opacity": ".7", "foreground": "rgba(0, 0, 0, .87)", "plot_background": "rgba(255, 255, 255, 1)", "value_label_font_size": 10, "value_label_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "background": "rgba(249, 249, 249, 1)", "no_data_font_size": 64, "value_colors": [], "guide_stroke_dasharray": "4,4", "transition": "150ms", "foreground_subtle": "rgba(0, 0, 0, .54)", "value_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "tooltip_font_family": "Consolas, \"Liberation Mono\", Menlo, Courier, monospace", "title_font_size": 16, "stroke_opacity_hover": ".9", "major_guide_stroke_dasharray": "6,6", "opacity_hover": ".8", "foreground_strong": "rgba(0, 0, 0, 1)"}, "x_label_rotation": 0, "fill": false, "missing_value_fill_truncation": "x", "zero": 0, "margin_right": null, "interpolation_parameters": {}, "x_labels_major": null, "rounded_bars": null, "show_y_labels": true, "dots_size": 2.5, "show_y_guides": true, "show_minor_y_labels": true, "x_labels": null, "y_title": null, "order_min": null, "formatter": null, "disable_xml_declaration": false, "strict": false, "css": ["file://style.css", "file://graph.css"], "tooltip_fancy_mode": true, "defs": [], "show_only_major_dots": false, "y_label_rotation": 0, "show_x_labels": true, "min_scale": 4, "show_x_guides": false, "spacing": 10, "x_labels_major_count": null, "pretty_print": false, "tooltip_border_radius": 0, "interpolate": null, "js": ["//kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js"], "y_labels": null, "stroke_style": null, "print_labels": false, "interpolation_precision": 250, "x_title": null, "y_labels_major_every": null, "logarithmic": false, "legends": ["Google Play", "Network Online", "Apple"], "max_scale": 16, "print_zeroes": true, "no_data_text": "No data", "truncate_legend": -1, "x_labels_major_every": null, "secondary_range": null, "legend_box_size": 12, "no_prefix": false, "stroke": true, "stack_from_top": false, "include_x_axis": false, "range": null, "classes": ["pygal-chart"], "margin_top": null, "margin_left": null, "y_labels_major_count": null, "margin_bottom": null, "inverse_y_axis": false, "margin": 20, "allow_interruptions": false, "print_values_position": "top"}</script><script type="text/javascript" xlink:href="https://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js"/></defs><title>Payments Per Gateway (in USD)</title><g class="graph bar-graph vertical"><rect class="background" height="600" width="800" x="0" y="0"/><g class="plot" transform="translate(193, 46)"><rect class="background" height="534" width="586.4" x="0" y="0"/><g class="axis y"><g class="guides"><path class="major line" d="M0.000000 523.730769 h586.400000"/><text class="major" x="-5" y="527.230769231">0$</text><title>0$</title></g><g class="guides"><path class="guide line" d="M0.000000 485.435050 h586.400000"/><text class="" x="-5" y="488.935050495">10$</text><title>10$</title></g><g class="guides"><path class="guide line" d="M0.000000 447.139332 h586.400000"/><text class="" x="-5" y="450.63933176">20$</text><title>20$</title></g><g class="guides"><path class="guide line" d="M0.000000 408.843613 h586.400000"/><text class="" x="-5" y="412.343613025">30$</text><title>30$</title></g><g class="guides"><path class="guide line" d="M0.000000 370.547894 h586.400000"/><text class="" x="-5" y="374.047894289">40$</text><title>40$</title></g><g class="guides"><path class="major guide line" d="M0.000000 332.252176 h586.400000"/><text class="major" x="-5" y="335.752175554">50$</text><title>50$</title></g><g class="guides"><path class="guide line" d="M0.000000 293.956457 h586.400000"/><text class="" x="-5" y="297.456456819">60$</text><title>60$</title></g><g class="guides"><path class="guide line" d="M0.000000 255.660738 h586.400000"/><text class="" x="-5" y="259.160738083">70$</text><title>70$</title></g><g class="guides"><path class="guide line" d="M0.000000 217.365019 h586.400000"/><text class="" x="-5" y="220.865019348">80$</text><title>80$</title></g><g class="guides"><path class="guide line" d="M0.000000 179.069301 h586.400000"/><text class="" x="-5" y="182.569300612">90$</text><title>90$</title></g><g class="guides"><path class="major guide line" d="M0.000000 140.773582 h586.400000"/><text class="major" x="-5" y="144.273581877">100$</text><title>100$</title></g><g class="guides"><path class="guide line" d="M0.000000 102.477863 h586.400000"/><text class="" x="-5" y="105.977863142">110$</text><title>110$</title></g><g class="guides"><path class="guide line" d="M0.000000 64.182144 h586.400000"/><text class="" x="-5" y="67.6821444064">120$</text><title>120$</title></g></g><g class="series serie-0 color-0"><g class="bars"><g class="bar"><rect class="rect reactive tooltip-trigger" height="497.078429185" rx="0" ry="0" width="145.547487179" x="55.0313846154" y="26.6523400457"/><desc class="value">130$</desc><desc class="x centered">127.805128205</desc><desc class="y centered">275.191554638</desc></g></g></g><g class="series serie-1 color-1"><g class="bars"><g class="bar"><rect class="rect reactive tooltip-trigger" height="306.365749883" rx="0" ry="0" width="145.547487179" x="220.42625641" y="217.365019348"/><desc class="value">80$</desc><desc class="x centered">293.2</desc><desc class="y centered">370.547894289</desc></g></g></g><g class="series serie-2 color-2"><g class="bars"><g class="bar"><rect class="rect reactive tooltip-trigger" height="248.539214593" rx="0" ry="0" width="145.547487179" x="385.821128205" y="275.191554638"/><desc class="value">65$</desc><desc class="x centered">458.594871795</desc><desc class="y centered">399.461161935</desc></g></g></g></g><g class="titles"><text class="title plot_title" x="400.0" y="26">Payments Per Gateway (in USD)</text></g><g class="plot overlay" transform="translate(193, 46)"><g class="series serie-0 color-0"/><g class="series serie-1 color-1"/><g class="series serie-2 color-2"/></g><g class="plot text-overlay" transform="translate(193, 46)"><g class="series serie-0 color-0"><text class="value" text-anchor="middle" x="127.805128205" y="23.9856733791">130$</text></g><g class="series serie-1 color-1"><text class="value" text-anchor="middle" x="293.2" y="214.698352681">80$</text></g><g class="series serie-2 color-2"><text class="value" text-anchor="middle" x="458.594871795" y="272.524887972">65$</text></g></g><g class="plot tooltip-overlay" transform="translate(193, 46)"><g class="tooltip" style="opacity: 0" transform="translate(0 0)"><rect class="tooltip-box" height="0" rx="0" ry="0" width="0"/><g class="text"/></g></g><g class="legends" transform="translate(10, 56)"><g class="legend reactive activate-serie" id="activate-serie-0"><rect class="color-0 reactive" height="12" width="12" x="0.0" y="1.0"/><text x="17.0" y="11.2">Google Play</text></g><g class="legend reactive activate-serie" id="activate-serie-1"><rect class="color-1 reactive" height="12" width="12" x="0.0" y="22.0"/><text x="17.0" y="32.2">Network Online</text></g><g class="legend reactive activate-serie" id="activate-serie-2"><rect class="color-2 reactive" height="12" width="12" x="0.0" y="43.0"/><text x="17.0" y="53.2">Apple</text></g></g><g class="legends" transform="translate(790, 56)"/></g></svg>
```

Any thoughts or ideas on how to fix this?

Thanks in advance.
//M

**Comment by arpit1997** [comment]
I also git the same kind of issue but ia have only python2.7 and python3.4 i ran my svg code but it got out of memory.
```
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 328, in draw
    TAGS[node.tag](self, node)
  File "/usr/local/lib/python2.7/site-packages/cairosvg/surface/text.py", line 90, in text
    surface.context.font_extents())
  File "/usr/local/lib/python2.7/site-packages/cairocffi/context.py", line 1929, in font_extents
    self._check_status()
  File "/usr/local/lib/python2.7/site-packages/cairocffi/context.py", line 108, in _check_status
    _check_status(cairo.cairo_status(self._pointer))
  File "/usr/local/lib/python2.7/site-packages/cairocffi/__init__.py", line 74, in _check_status
    raise exception(message, status)
MemoryError: ('cairo returned CAIRO_STATUS_NO_MEMORY: out of memory', 1)
```
did you find out any solution @sergani If so ping me.
:smile_cat: :smile_cat:

**Comment by sergani** [comment]
Not yet, looking forward to some support.

Thanks
//M

**Comment by liZe** [comment]
I'm (unsurprisingly) not able to get the same error, with both `1.0.x` and `master`.

From various sources on Internet, it may come from:
- cffi not always being thread-safe,
- cairo not always being thread-safe,
- cairo being stupid with fonts on Windows.

Unfortunately, you're probably not in any of these cases. So… Getting the latest versions of Python, cffi, cairocffi and cairo is probably the way to go. Trying the current `master` branch (Python 3 only) can help. But I'm afraid there's nothing to be done in CairoSVG :sad:.

Also see Kozea/cairocffi#22.

**Comment by sergani** [comment]
That is quite a dead end.
I tried a few different things but never got it to work.
Strangely this script was copied from another server that's long been
erased, and was working fine there.

Thanks
//M

**Comment by ErikOnBike** [comment]
Have you tried changing the fonts in the SVG? It seems Cairo has difficulties reading the font_extents (seeing the stack trace). You might also try to (re)install fonts (FreeType).

See also (old post): https://answers.launchpad.net/graphite/+question/38833

**Comment by sergani** [comment]
What can I say, thank you man.
I followed the link, and installed bitmap-fonts via yum, it fixed the issue.

Thanks
//M

**Comment by andChow** [comment]
I had the same question, The question cause by system fonts

**Comment by discover59** [comment]
I same error recently and it disappeared after removing all `tspan` tags.
