### ISSUE TITLE
Unable to install 2.0.0

### ISSUE THREAD

**Issue by kjmph** [Kozea/CairoSVG#129]
I am getting the following error on my Mac:

```
$ pip install --upgrade CairoSVG
Collecting CairoSVG
  Using cached CairoSVG-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s9/7xm7w3p1559_czcgw1wxc1q80000gn/T/pip-build-9rEMk2/CairoSVG/setup.py", line 24, in <module>
        with open(init_path, 'r', encoding='utf-8') as fd:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s9/7xm7w3p1559_czcgw1wxc1q80000gn/T/pip-build-9rEMk2/CairoSVG/
```

Did you intend to `import io` and use `io.open`?

**Comment by liZe** [comment]
CairoSVG 2.0.0 only works with Python 3.4+, and doesn't support 2.7. I you can't use Python 3, please install CairoSVG 1.x.
