### ISSUE TITLE
Error installing on MacOSX

### ISSUE THREAD

**Issue by mudcube** [Kozea/CairoSVG#137]
I'm running into the following issue installing on MacOSX, any ideas?
```
$ pip install cairosvg
Collecting cairosvg
  Downloading CairoSVG-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-3Zvrc6/cairosvg/setup.py", line 24, in <module>
        with open(init_path, 'r', encoding='utf-8') as fd:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-3Zvrc6/cairosvg/
```

**Comment by mudcube** [comment]
Duplicate.

**Comment by mudcube** [comment]
Solution: `python3.5 -m pip install cairosvg`
