### ISSUE TITLE
IndexError while installing

### ISSUE THREAD

**Issue by iBlueDust** [Kozea/CairoSVG#172]
using "pip install cairosvg" (Yes, its using pip 3.6) returns an Index out of range exception.

```
Collecting cairosvg
  Using cached CairoSVG-2.1.3-py3-none-any.whl
Collecting defusedxml (from cairosvg)
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Collecting cssselect2 (from cairosvg)
  Using cached cssselect2-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: pillow in c:\users\hp\appdata\roaming\python\python36\site-packages (from cairosvg)
Collecting tinycss2 (from cairosvg)
  Downloading tinycss2-0.6.1-py2.py3-none-any.whl (61kB)
Collecting cairocffi (from cairosvg)
  Using cached cairocffi-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 477, in __init__
        self.vc_ver = self.find_available_vc_vers()[-1]
    IndexError: list index out of range
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\hp\AppData\Local\Temp\easy_install-6z9mx3_7\cffi-1.11.4\setup.py", line 116, in <module>
      File "C:\Users\hp\AppData\Local\Temp\easy_install-6z9mx3_7\cffi-1.11.4\setup.py", line 94, in uses_msvc
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\command\config.py", line 227, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\command\config.py", line 133, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 172, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 771, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 480, in __init__
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hp\AppData\Local\Temp\pip-build-acrib6fp\cairocffi\setup.py", line 44, in <module>
        extras_require={'xcb': ['xcffib>=0.3.2']},
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\hp\AppData\Local\Temp\easy_install-6z9mx3_7\cffi-1.11.4\setup.py", line 116, in <module>
      File "C:\Users\hp\AppData\Local\Temp\easy_install-6z9mx3_7\cffi-1.11.4\setup.py", line 94, in uses_msvc
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\command\config.py", line 227, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\command\config.py", line 133, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 172, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 771, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 480, in __init__
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\hp\AppData\Local\Temp\pip-build-acrib6fp\cairocffi\
```

**Comment by liZe** [comment]
As said in the backtrace, you should install Microsoft Visual C++ 14.0 (you even have a link to download it :wink:).
