### ISSUE TITLE
unknown locale: UTF-8

### ISSUE THREAD

**Issue by marekkowalczyk** [Kozea/CairoSVG#207]
MacOS 10.14

[The offending file is attached](https://github.com/Kozea/CairoSVG/files/2467675/8-fig-2.svg.zip)

**Command line I/O**
```
$ cairosvg 8-fig-2.svg -o 8-fig-2.pdf
Traceback (most recent call last):
  File "/usr/local/bin/cairosvg", line 7, in <module>
    from cairosvg.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/cairosvg/__init__.py", line 41, in <module>
    from . import surface  # noqa
  File "/usr/local/lib/python3.7/site-packages/cairosvg/surface.py", line 27, in <module>
    from .defs import (
  File "/usr/local/lib/python3.7/site-packages/cairosvg/defs.py", line 24, in <module>
    from .bounding_box import calculate_bounding_box, is_non_empty_bounding_box
  File "/usr/local/lib/python3.7/site-packages/cairosvg/bounding_box.py", line 26, in <module>
    from .features import match_features
  File "/usr/local/lib/python3.7/site-packages/cairosvg/features.py", line 25, in <module>
    LOCALE = locale.getdefaultlocale()[0] or ''
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 568, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by liZe** [comment]
Hello, and thank you for this bug report!

Unfortunately, I can't reproduce your problem, and I think that it's not directly related to CairoSVG. Your problem happens in Python's default library, and you should be able to reproduce it with this simple Python script:

```python
import locale
locale.getdefaultlocale()
```

I think that there's something wrong in Python with macOS. Please check [this StackOverflow thread](https://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8#19961403) and [this bug report](https://bugs.python.org/issue18378).
