### ISSUE TITLE
CairoSVG 1.0.22 install broken with pip on Python 2.7

### ISSUE THREAD

**Issue by tirkarthi** [Kozea/CairoSVG#232]
We are using `CairoSVG==1.0.22` in our requirements with Python 2.7 and suddenly it causes failure on installing from pip. It seems that there is an error introduced with c93eb812ab54ab6666cbeb1c8eb64934c3cc4544 and this was also seems to be pushed to PyPI as 1.0.0 thus causing the failure. It would be helpful to know if the change to older version to introduce this error is intentional and if so how we can proceed with installing a compatible version.

Installation traceback : 

```
pip install --ignore-installed CairoSVG==1.0.22
Collecting CairoSVG==1.0.22
Collecting cairocffi (from CairoSVG==1.0.22)
  Using cached https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2b/mhgtnnpx4z943t4cc9yvw4qw0000gn/T/pip-build-kINqDH/cairocffi/setup.py", line 7, in <module>
        'cairocffi does not support Python 2.x anymore. '
    RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2b/mhgtnnpx4z943t4cc9yvw4qw0000gn/T/pip-build-kINqDH/cairocffi/
```

File from PyPI : 

```
(virtual-next) ➜  wget https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
--2019-02-11 18:28:48--  https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
Resolving files.pythonhosted.org... 151.101.129.63, 151.101.1.63, 151.101.193.63, ...
Connecting to files.pythonhosted.org|151.101.129.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68570 (67K) [binary/octet-stream]
Saving to: ‘cairocffi-1.0.0.tar.gz’

cairocffi-1.0.0.tar.gz      100%[=========================================>]  66.96K   242KB/s    in 0.3s

2019-02-11 18:28:49 (242 KB/s) - ‘cairocffi-1.0.0.tar.gz’ saved [68570/68570]

(virtual-next) ➜  tar xvf cairocffi-1.0.0.tar.gz
x cairocffi-1.0.0/
x cairocffi-1.0.0/LICENSE
x cairocffi-1.0.0/PKG-INFO
x cairocffi-1.0.0/README.rst
x cairocffi-1.0.0/cairocffi/
x cairocffi-1.0.0/cairocffi/VERSION
x cairocffi-1.0.0/cairocffi/__init__.py
x cairocffi-1.0.0/cairocffi/constants.py
x cairocffi-1.0.0/cairocffi/context.py
x cairocffi-1.0.0/cairocffi/ffi_build.py
x cairocffi-1.0.0/cairocffi/fonts.py
x cairocffi-1.0.0/cairocffi/matrix.py
x cairocffi-1.0.0/cairocffi/patterns.py
x cairocffi-1.0.0/cairocffi/pixbuf.py
x cairocffi-1.0.0/cairocffi/surfaces.py
x cairocffi-1.0.0/cairocffi/test_cairo.py
x cairocffi-1.0.0/cairocffi/test_pixbuf.py
x cairocffi-1.0.0/cairocffi/test_xcb.py
x cairocffi-1.0.0/cairocffi/xcb.py
x cairocffi-1.0.0/cairocffi.egg-info/
x cairocffi-1.0.0/cairocffi.egg-info/PKG-INFO
x cairocffi-1.0.0/cairocffi.egg-info/SOURCES.txt
x cairocffi-1.0.0/cairocffi.egg-info/dependency_links.txt
x cairocffi-1.0.0/cairocffi.egg-info/requires.txt
x cairocffi-1.0.0/cairocffi.egg-info/top_level.txt
x cairocffi-1.0.0/setup.cfg
x cairocffi-1.0.0/setup.py
(virtual-next) ➜  cd cairocffi-1.0.0
(virtual-next) ➜  cairocffi-1.0.0 grep -i 'support ' setup.py
        'cairocffi does not support Python 2.x anymore. '
```

Thanks

Edit : changed commit to correct commit c93eb812ab54ab6666cbeb1c8eb64934c3cc4544

**Comment by tirkarthi** [comment]
Thanks @liZe for transferring this. I initially misunderstood the issue that cairocffi was published with new code under an older version causing the reported issue.

**Comment by liZe** [comment]
Strange, I get no error, cairocffi-0.9.0 is automatically used instead of cairocffi-1.0.0:
```
pip install --ignore-installed CairoSVG==1.0.22
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting CairoSVG==1.0.22
Collecting cairocffi (from CairoSVG==1.0.22)
Collecting cffi>=1.1.0 (from cairocffi->CairoSVG==1.0.22)
  Using cached https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.1.0->cairocffi->CairoSVG==1.0.22)
Installing collected packages: pycparser, cffi, cairocffi, CairoSVG
Successfully installed CairoSVG-1.0.22 cairocffi-0.9.0 cffi-1.11.5 pycparser-2.19
```

What's your version of pip?

**Comment by tirkarthi** [comment]
* pip version

```
(virtual-next) ➜  pip --version
pip 8.1.2 from /Users/karthikeyansingaravelan/happyfox/virtual-next/lib/python2.7/site-packages (python 2.7)
```

* Python version

```python
(virtual-next) ➜  python
Python 2.7.14 (default, Mar 12 2018, 13:54:56)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
```

```
(virtual-next) ➜  pip install --ignore-installed --no-cache-dir CairoSVG==1.0.22
Collecting CairoSVG==1.0.22
  Downloading https://files.pythonhosted.org/packages/d9/9b/c241990c86faa9e52a01f0570bba4247ba0f3d66eae2607e179cb9ae773a/CairoSVG-1.0.22.tar.gz
Collecting cairocffi (from CairoSVG==1.0.22)
  Downloading https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 139kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2b/mhgtnnpx4z943t4cc9yvw4qw0000gn/T/pip-build-iY4yXo/cairocffi/setup.py", line 7, in <module>
        'cairocffi does not support Python 2.x anymore. '
    RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2b/mhgtnnpx4z943t4cc9yvw4qw0000gn/T/pip-build-iY4yXo/cairocffi/
You are using pip version 8.1.2, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Strangely, upgrading pip seems to work correctly and falling back to 8.1.2 causes the error.

```
(virtual-next) ➜  pip install -U pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d7/41/34dd96bd33958e52cb4da2f1bf0818e396514fd4f4725a79199564cd0c20/pip-19.0.2-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 104kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-19.0.2
(virtual-next) ➜  pip install --ignore-installed --no-cache-dir CairoSVG==1.0.22
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting CairoSVG==1.0.22
  Downloading https://files.pythonhosted.org/packages/d9/9b/c241990c86faa9e52a01f0570bba4247ba0f3d66eae2607e179cb9ae773a/CairoSVG-1.0.22.tar.gz
Collecting cairocffi (from CairoSVG==1.0.22)
  Downloading https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6/cairocffi-0.9.0.tar.gz (84kB)
    100% |████████████████████████████████| 92kB 60kB/s
Collecting cffi>=1.1.0 (from cairocffi->CairoSVG==1.0.22)
  Downloading https://files.pythonhosted.org/packages/7e/4a/b647e46faaa2dcfb16069b6aad2d8509982fd63710a325b8ad7db80f18be/cffi-1.11.5-cp27-cp27m-macosx_10_6_intel.whl (238kB)
    100% |████████████████████████████████| 245kB 105kB/s
Collecting pycparser (from cffi>=1.1.0->cairocffi->CairoSVG==1.0.22)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 132kB/s
weasyprint 0.21 has requirement html5lib>=0.999, but you'll have html5lib 0.90 which is incompatible.
Installing collected packages: pycparser, cffi, cairocffi, CairoSVG
  Running setup.py install for pycparser ... done
  Running setup.py install for cairocffi ... done
  Running setup.py install for CairoSVG ... done
Successfully installed CairoSVG-1.0.22 cairocffi-0.9.0 cffi-1.11.5 pycparser-2.19
```

**Comment by liZe** [comment]
Pip 8.1.2 is not that old, but I suppose there's a feature missing or a bug that causes this behavior. As I don't want to support old Pip versions :angel:, you can close this issue if it's OK for you.

**Comment by tirkarthi** [comment]
We upgraded pip along with adding cairocffi in the requirements file with the necessary version at the top and it works fine. I am closing this. Thanks a lot for your help.

**Comment by alexdemi** [comment]
Guys\girls! Urgent !!!
What is the lowest version of PIP I should use for Python 2.7 to install correctly CairoSVG==1.0.22
Thanks !

**Comment by liZe** [comment]
> What is the lowest version of PIP I should use for Python 2.7 to install correctly CairoSVG==1.0.22

I don't know. Try in a virtualenv!
