### ISSUE TITLE
Embedded images broken on Windows

### ISSUE THREAD

**Issue by TWAC** [Kozea/CairoSVG#234]
After upgrading to the latest CairoSVG I started getting errors.
I created a small testcase, and bisected that.

```python
import cairosvg

svg = """<?xml version="1.0" encoding="UTF-8"?>
<svg width="26mm" height="37mm" version="1.1" viewBox="0 0 26 37" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <g transform="translate(0,-260)">
  <image x="7.6102" y="267.88" width="2.6458" height="2.6458" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3/F3+AAAABlBMVEX///8AAABVwtN+AAAAEUlE QVQI12P4f4ABiHgYsCIAY1cD3831LVcAAAAASUVORK5CYII= "/>
  <text x="10.787534" y="270.40604" fill="#000000" font-family="sans-serif" font-size="3.4703px" letter-spacing="0px" stroke-width=".086757" word-spacing="0px" style="line-height:1.25" xml:space="preserve"><tspan x="10.787534" y="270.40604" stroke-width=".086757">EST</tspan></text>
 </g>
</svg>"""

png = cairosvg.svg2png(svg)
```

```
Traceback (most recent call last):
  File "broken-cairosvg.py", line 15, in <module>
    png = cairosvg.svg2png(svg)
  File "C:\Python37\lib\site-packages\cairosvg\__init__.py", line 70, in svg2png
    output_height=output_height)
  File "C:\Python37\lib\site-packages\cairosvg\surface.py", line 148, in convert
    output_width, output_height)
  File "C:\Python37\lib\site-packages\cairosvg\surface.py", line 221, in __init__
    self.draw(tree)
  File "C:\Python37\lib\site-packages\cairosvg\surface.py", line 459, in draw
    self.draw(child)
  File "C:\Python37\lib\site-packages\cairosvg\surface.py", line 459, in draw
    self.draw(child)
  File "C:\Python37\lib\site-packages\cairosvg\surface.py", line 393, in draw
    TAGS[node.tag](self, node)
  File "C:\Python37\lib\site-packages\cairosvg\image.py", line 43, in image
    url = parse_url(node.get('{http://www.w3.org/1999/xlink}href'), base_url)
  File "C:\Python37\lib\site-packages\cairosvg\url.py", line 138, in parse_url
    url = normalize_url(url.strip('\'"'))
  File "C:\Python37\lib\site-packages\cairosvg\url.py", line 55, in normalize_url
    url = Path(url).resolve().as_uri()
  File "C:\Python37\lib\pathlib.py", line 1134, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Python37\lib\pathlib.py", line 192, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\temp\\data:image\\png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3\\F3+AAAABlBMVEX\\8AAABVwtN+AAAAEUlE QVQI12P4f4ABiHgYsCIAY1cD3831LVcAAAAASUVORK5CYII='
```
```
git bisect start
# good: [371ddc0fdebcb66cbdd6a5a9499a13890c96930e] Version 2.1.3
git bisect good 371ddc0fdebcb66cbdd6a5a9499a13890c96930e
# bad: [ed92813c78e282139a0d47061b1ffbbb77fbb1df] Fix tests
git bisect bad ed92813c78e282139a0d47061b1ffbbb77fbb1df
# bad: [c463ef1db6d7c8943bb895e5d4ce51207b2157b9] Fix unsafe parameter in svg2ps
git bisect bad c463ef1db6d7c8943bb895e5d4ce51207b2157b9
# bad: [2354457d1b1e0d220c8023affdfa73f5b1b79601] Merge branch 'master' into 'gsbabil/fix-windows-path-issues'
git bisect bad 2354457d1b1e0d220c8023affdfa73f5b1b79601
# skip: [a3f2543360b96ec468259a57c8753f81532f2ca0] Ignore temp file delete error while testing
git bisect skip a3f2543360b96ec468259a57c8753f81532f2ca0
# good: [58c7bb5e6c0a82a620f02757e61a953146f2d8c4] Don't forget the unsafe parameter of svg2* functions
git bisect good 58c7bb5e6c0a82a620f02757e61a953146f2d8c4
# skip: [255853085848001ea64ceea67c5ac20c349c5729] Fix isort and flake8 issues
git bisect skip 255853085848001ea64ceea67c5ac20c349c5729
# skip: [640b1a47a3c27133abaf7f7256b2ef66486b032f] Fix incompatible path related errors on Windows/NT
git bisect skip 640b1a47a3c27133abaf7f7256b2ef66486b032f
# skip: [552a3d4855e16f2aecd4684a92ae882f63d52dd3] Fix regression tests on Windows/NT
git bisect skip 552a3d4855e16f2aecd4684a92ae882f63d52dd3
# skip: [4047ec2c4bbaa8dea5b1073cb460a0dc3c1bdec6] Add more aggressive SVG file detection
git bisect skip 4047ec2c4bbaa8dea5b1073cb460a0dc3c1bdec6
# good: [b435cd54bf0d09a11be873c39937994379480474] Fix T paths (again!)
git bisect good b435cd54bf0d09a11be873c39937994379480474
# only skipped commits left to test
# possible first bad commit: [2354457d1b1e0d220c8023affdfa73f5b1b79601] Merge branch 'master' into 'gsbabil/fix-windows-path-issues'
# possible first bad commit: [a3f2543360b96ec468259a57c8753f81532f2ca0] Ignore temp file delete error while testing
# possible first bad commit: [255853085848001ea64ceea67c5ac20c349c5729] Fix isort and flake8 issues
# possible first bad commit: [552a3d4855e16f2aecd4684a92ae882f63d52dd3] Fix regression tests on Windows/NT
# possible first bad commit: [640b1a47a3c27133abaf7f7256b2ef66486b032f] Fix incompatible path related errors on Windows/NT
# possible first bad commit: [4047ec2c4bbaa8dea5b1073cb460a0dc3c1bdec6] Add more aggressive SVG file detection
```

**Comment by liZe** [comment]
Thanks a lot for your very clear bug report. Feel free to test the fix and tell me if it works for you.

**Comment by TWAC** [comment]
Yes, master works fine now, thanks.
