### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2

### ISSUE THREAD

**Issue by saomantou** [Kozea/CairoSVG#237]
>>> import cairosvg

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    import cairosvg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cairosvg\__init__.py", line 42, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cairosvg\surface.py", line 25, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cairocffi\__init__.py", line 39, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2', 'cairo.so.2')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cairocffi\__init__.py", line 36, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2

![QQ截图20190504144252](https://user-images.githubusercontent.com/26544893/57175168-56ee4780-6e7b-11e9-9ce4-65e03044bf42.jpg)

**Comment by liZe** [comment]
Could you try to follow [WeasyPrint's installation chapter](https://weasyprint.readthedocs.io/en/latest/install.html#windows)? I'll automatically install CairoSVG.

**Comment by Senpos** [comment]
I have exactly the same problem on Windows 7 & Python 3.7.
Gonna try the recommendation from @liZe
