### ISSUE TITLE
cairo not found

### ISSUE THREAD

**Issue by shrx** [Kozea/CairoSVG#28]
```
cairosvg rpi_cam_body01.svg  -o test.pdf
Traceback (most recent call last):
  File "/usr/local/bin/cairosvg", line 24, in <module>
    import cairosvg
  File "/Library/Python/2.7/site-packages/cairosvg/__init__.py", line 27, in <module>
    from . import surface
  File "/Library/Python/2.7/site-packages/cairosvg/surface/__init__.py", line 23, in <module>
    import cairo
ImportError: No module named cairo
```

**Comment by marvinmirtschin** [comment]
```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cairosvg\surface\__init__.py", line 25, in <module>
    import cairocffi as cairo
  File "C:\Python34\lib\site-packages\cairocffi\__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "C:\Python34\lib\site-packages\cairocffi\__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mm\Documents\cairotest.py", line 1, in <module>
    import cairosvg
  File "C:\Python34\lib\site-packages\cairosvg\__init__.py", line 27, in <module>
    from . import surface
  File "C:\Python34\lib\site-packages\cairosvg\surface\__init__.py", line 30, in <module>
    import cairo  # pycairo
  File "C:\Python34\lib\site-packages\cairo\__init__.py", line 19, in <module>
    from ._cairo import *
ImportError: No module named 'cairo._cairo'
```
