### ISSUE TITLE
Error with link to local file

### ISSUE THREAD

**Issue by FlachyJoe** [Kozea/CairoSVG#293]
Hi,
I got an issue when I try to convert an assembly of 4 svg files. My assembly file looks like this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg997">
  <image
     xlink:href="Page_1.svg"
     id="page1"
     x="-74.25"
     y="0"
     width="74.25"
     height="105"
     transform="rotate(-90)" />
  <image
     xlink:href="Page_2.svg"
     id="page2"
     x="-74.25"
     y="105"
     width="74.25"
     height="105"
     transform="rotate(-90)" />
  <image
     xlink:href="Page_3.svg"
     image-rendering="svg"
     id="page3"
     x="222.75"
     y="-210"
     width="74.25"
     height="210"
     transform="rotate(90)" />
  <image
     xlink:href="Page_4.svg"
     id="page4"
     x="0"
     y="74.25"
     width="210"
     height="148.5" />
</svg>
```

And here is the traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1507, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/Page_1.svg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cairosvg", line 11, in <module>
    load_entry_point('CairoSVG==2.4.2', 'console_scripts', 'cairosvg')()
  File "/usr/lib/python3/dist-packages/cairosvg/__main__.py", line 83, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/usr/lib/python3/dist-packages/cairosvg/surface.py", line 146, in convert
    instance = cls(
  File "/usr/lib/python3/dist-packages/cairosvg/surface.py", line 212, in __init__
    self.draw(tree)
  File "/usr/lib/python3/dist-packages/cairosvg/surface.py", line 449, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface.py", line 383, in draw
    TAGS[node.tag](self, node)
  File "/usr/lib/python3/dist-packages/cairosvg/image.py", line 44, in image
    image_bytes = node.fetch_url(url, 'image/*')
  File "/usr/lib/python3/dist-packages/cairosvg/parser.py", line 258, in fetch_url
    return read_url(url, self.url_fetcher, resource_type)
  File "/usr/lib/python3/dist-packages/cairosvg/url.py", line 159, in read_url
    return url_fetcher(url, resource_type)
  File "/usr/lib/python3/dist-packages/cairosvg/url.py", line 100, in fetch
    return urlopen(Request(url, headers=HTTP_HEADERS)).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1485, in file_open
    return self.open_local_file(req)
  File "/usr/lib/python3.8/urllib/request.py", line 1524, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/Page_1.svg'>
```

Thanks !

**Comment by liZe** [comment]
Hello!

There’s a problem in the way relative URIs are resolved with your SVG, probably because you don’t use CairoSVG with a real file or URI. You really should use absolute URIs in `href`s.

**Comment by FlachyJoe** [comment]
Thank for the reply.
Assembly.svg and Page_#.svg are store in the same folder, so it should work with these URIs.
I found a workaround by adding `./` in front of filenames:
 `cairosvg ./assembly.svg -o ./assembly.pdf`

However, I can't use cairosvg due to the transparency rendering.

**Comment by liZe** [comment]
> I found a workaround by adding `./` in front of filenames:
> `cairosvg ./assembly.svg -o ./assembly.pdf`

Wow, that’s strange. Thanks for reporting, I’ll try to reproduce the bug.

> However, I can't use cairosvg due to the transparency rendering.

I’d be glad to know what’s wrong, and maybe find a way to fix that!

**Comment by FlachyJoe** [comment]
I'm sending you the faulty files by mail.
