### ISSUE TITLE
Error converting valid SVG

### ISSUE THREAD

**Issue by 0x5c** [Kozea/CairoSVG#303]
I have a project where I need to convert [this  SVG image](https://prop.kc2g.com/renders/current/mufd-normal-now.svg) into a PNG file.
The SVG is valid (according to the [W3C MArkup Validator](https://validator.w3.org/)), yet it causes CairoSVG to fail with this error: `TypeError: No tag with id="DejaVuSans-32" found.`

Using `svg2png()` with a bytestring containing the image.

### Details
Python 3.9.0
CairoSVG 2.5.0

It seems that the image is generated by matplotlib

### Traceback
```none
Traceback (most recent call last):
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/mnt/s/code/bots/qrm/qrm2/exts/propagation.py", line 31, in mufmap
    out = BytesIO(cairosvg.svg2png(bytestring=svg))
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/surface.py", line 131, in convert
    instance = cls(
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/surface.py", line 213, in __init__
    self.draw(tree)
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/surface.py", line 459, in draw
    self.draw(child)
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/surface.py", line 459, in draw
    self.draw(child)
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/surface.py", line 459, in draw
    self.draw(child)
  [Previous line repeated 1 more time]
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/surface.py", line 391, in draw
    TAGS[node.tag](self, node)
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/defs.py", line 349, in use
    tree = Tree(
  File "/mnt/s/code/bots/qrm/qrm2/botenv/lib/python3.9/site-packages/cairosvg/parser.py", line 403, in __init__
    raise TypeError(
TypeError: No tag with id="DejaVuSans-32" found.
```

**Comment by liZe** [comment]
It’s fixed.

For the record: I suppose that `DejaVuSans-32` references the 32nd character of the DejaVu Sans font. Character 32 is … the space 😉.

**Comment by 0x5c** [comment]
Ah, I see
Doing some searching, it seems that matplotlib's SVG output isn't quite the cleanest
Thanks a lot for the fix!
