### ISSUE TITLE
The IsADirectoryError exception

### ISSUE THREAD

**Issue by rusfearuth** [Kozea/CairoSVG#305]
I have a problem with using CairoSVG (2.5.0) on my mac with Python 3.9.0.

When I try to use command from the example
```bash
cairosvg my.svg -o my.png
```
I get the next error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1514, in open_local_file
    return addinfourl(open(localfile, 'rb'), headers, origurl)
IsADirectoryError: [Errno 21] Is a directory: '/Users/myuser/Sources'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 131, in convert
    instance = cls(
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 213, in __init__
    self.draw(tree)
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 459, in draw
    self.draw(child)
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 459, in draw
    self.draw(child)
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 459, in draw
    self.draw(child)
  [Previous line repeated 6 more times]
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 391, in draw
    TAGS[node.tag](self, node)
  File "/usr/local/lib/python3.9/site-packages/cairosvg/defs.py", line 349, in use
    tree = Tree(
  File "/usr/local/lib/python3.9/site-packages/cairosvg/parser.py", line 386, in __init__
    bytestring = self.fetch_url(
  File "/usr/local/lib/python3.9/site-packages/cairosvg/parser.py", line 243, in fetch_url
    return read_url(url, self.url_fetcher, resource_type)
  File "/usr/local/lib/python3.9/site-packages/cairosvg/url.py", line 143, in read_url
    return url_fetcher(url, resource_type)
  File "/usr/local/lib/python3.9/site-packages/cairosvg/url.py", line 84, in fetch
    return urlopen(Request(url, headers=HTTP_HEADERS)).read()
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1477, in file_open
    return self.open_local_file(req)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1516, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 21] Is a directory: '/Users/myuser/Sources'>
```
I get the same error if I use the CairoSVG as a library.

**Comment by liZe** [comment]
Hello!

Could you share your SVG file, please? Thank you!

**Comment by glisignoli** [comment]
I get the same thing with this svg: https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/bo.svg

**Comment by liZe** [comment]
> I get the same thing with this svg: https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/bo.svg

This problem happens because this file has `use` tags with no `href` attribute.

@rusfearuth feel free to reopen if your problem is different.
