### ISSUE TITLE
setup.py fails on python 3.9

### ISSUE THREAD

**Issue by ddevault** [Kozea/CairoSVG#320]
I think this is an issue with setup.cfg.

```
Traceback (most recent call last):
  File "/home/sircmpwn/sources/sr.ht-apkbuilds/sr.ht/py3-cairosvg/src/CairoSVG-2.5.1/setup.py", line 26, in <module>
    setup()
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 715, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/usr/lib/python3.9/site-packages/setuptools/config.py", line 152, in parse_configuration
    options.parse()
  File "/usr/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.9/site-packages/setuptools/config.py", line 668, in parse_section_entry_points
    self['entry_points'] = parsed
  File "/usr/lib/python3.9/site-packages/setuptools/config.py", line 210, in __setitem__
    raise KeyError(option_name)
KeyError: 'entry_points'
```

**Comment by liZe** [comment]
Hello!

It really looks like a bug in setuptools. Could you try to update setuptools and try to install it again?

**Comment by ddevault** [comment]
I am using an up-to-date setuptools.

**Comment by liZe** [comment]
I can’t reproduce, but I have this warning:

```
UserWarning: Usage of dash-separated 'console-scripts' will not be supported in future versions. Please use the underscore name 'console_scripts' instead
```

Could you please try to replace 'console-scripts' by 'console_scripts' in `setup.cfg` and try to launch `setup.py` again?

**Comment by ddevault** [comment]
Are you using Python 3.9? This issue is reproducible on Alpine Linux.

**Comment by liZe** [comment]
I use Python 3.9.3 with setuptools 56.0.0.

**Comment by ddevault** [comment]
I see. Well, I have torn down the environment in which this error could be reproduced. I will revisit this when I have another opportunity, and re-open it if still reproducible then.
