### ISSUE TITLE
Conversion of multiple files halted with error

### ISSUE THREAD

**Issue by GrimPixel** [Kozea/CairoSVG#410]
This is my repository: https://codeberg.org/GrimPixel/Tabletop_Club_Text_Asset_Generator
It was meant to generate vector graphs from texts, then convert them to raster graphs. When running the script `generate.py`, vector graphs are all generated successfully, two graphs are converted and I got an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1716, in close
    self.parser.Parse(b"", True) # end of data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Tabletop_Club_Text_Asset_Generator/generate.py", line 63, in <module>
    svg2png(url=s_vector_graph_file_name, write_to=s_raster_graph_directory_file_name)
  File "/home/user/venv/lib/python3.11/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/cairosvg/surface.py", line 129, in convert
    tree = Tree(
           ^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib/python3.11/site-packages/defusedxml/common.py", line 127, in fromstring
    return parser.close()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1718, in close
    self._raiseerror(v)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

```

**Comment by liZe** [comment]
Hi!

The problem is not in CairoSVG but in your script: the `.svg` files are not written on disk yet when you call `svg2png`.

If you want to [write files](https://codeberg.org/GrimPixel/Tabletop_Club_Text_Asset_Generator/src/branch/main/generate.py#L41) and be sure that everything is actually written on disk, you either have to call `close()` when all `write()` functions have been called, or use `with` as you did above (better).

Even better: don’t use `open`. Use [Pathlib](https://docs.python.org/3/library/pathlib.html) to manage your files and [Pathlib’s `write_text`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text) to write text: no low-level file descriptors anymore!

**Comment by GrimPixel** [comment]
Hi. Thank you for pointing the problem out and giving the advice.
