### ISSUE TITLE
OSError: no library called "cairo-2" was found

### ISSUE THREAD

**Issue by 12345-mcpython** [Kozea/CairoSVG#412]
gtk3 runtime has been installed

python 3.11.2 windows 11

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\software\Python310\Lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\software\Python310\Lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\software\Python310\Lib\site-packages\cairocffi\__init__.py", line 47, in <module>
    cairo = dlopen(
            ^^^^^^^
  File "C:\software\Python310\Lib\site-packages\cairocffi\__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'libcairo-2.dll': error 0x7f
cannot load library 'libcairo.so.2': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': error 0x7f

**Comment by liZe** [comment]
This is fixed by Kozea/cairocffi#221, release coming soon!
