### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by dkbarn** [Kozea/CairoSVG#413]
The file at https://upload.wikimedia.org/wikipedia/commons/e/e0/Vine_logo.svg is throwing a RecursionError when calling `cairosvg.svg2png`. 

This occurs with **cairosvg 2.7.1**

Here's a full example demonstrating the problem:

```python
import requests
import cairosvg

response = requests.get("https://upload.wikimedia.org/wikipedia/commons/e/e0/Vine_logo.svg")
cairosvg.svg2png(bytestring=response.content)
```

The full stacktrace of the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/surface.py", line 133, in convert
    instance = cls(
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/surface.py", line 225, in __init__
    self.draw(tree)
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/surface.py", line 472, in draw
    self.draw(child)
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/surface.py", line 440, in draw
    if not gradient_or_pattern(self, node, paint_source, fill_opacity):
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/defs.py", line 73, in gradient_or_pattern
    update_def_href(surface, name, surface.gradients)
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/defs.py", line 37, in update_def_href
    update_def_href(surface, href, def_dict)
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/defs.py", line 37, in update_def_href
    update_def_href(surface, href, def_dict)
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/defs.py", line 37, in update_def_href
    update_def_href(surface, href, def_dict)
  [Previous line repeated 983 more times]
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/defs.py", line 35, in update_def_href
    href = parse_url(def_node.get_href()).fragment
  File "/share/.venv/lib/python3.10/site-packages/cairosvg/url.py", line 140, in parse_url
    return urlparse(url or '')
  File "/usr/lib/python3.10/urllib/parse.py", line 400, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python3.10/urllib/parse.py", line 477, in urlsplit
    cached = _parse_cache.get(key, None)
RecursionError: maximum recursion depth exceeded in comparison
```

For reference, the contents of the svg:
```xml
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" height="208px" width="202px" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 202 208">
 <defs>
  <linearGradient id="a" y2="200" xlink:href="#a" gradientUnits="userSpaceOnUse" x2="100" x1="100">
   <stop stop-color="#00D59F" offset="0"/>
   <stop stop-color="#00AA80" offset="1"/>
  </linearGradient>
  <linearGradient id="c" y2="203.6" gradientUnits="userSpaceOnUse" x2="100" y1="-3.6" x1="100">
   <stop stop-color="#00ffbf" offset="0"/>
   <stop stop-color="#3d4d48" offset="1"/>
  </linearGradient>
  <linearGradient id="b" y2="200" xlink:href="#a" gradientUnits="userSpaceOnUse" x2="100" x1="100"/>
  <linearGradient id="d" y2="203.6" gradientUnits="userSpaceOnUse" x2="100" y1="-3.6" x1="100">
   <stop stop-color="#00ffbf" offset="0"/>
   <stop stop-color="#444" offset="1"/>
  </linearGradient>
  <filter id="e">
   <feGaussianBlur stdDeviation="0.5"/>
  </filter>
 </defs>
 <rect rx="30" height="203" width="200" y="2.5" x="1" fill="url(#d)"/>
 <rect rx="30" height="204" filter="url(#e)" width="200" y="2" x="1" fill="url(#c)"/>
 <rect rx="30" height="200" width="200" y="4" x="1" fill="url(#b)"/>
 <path fill="#1b896d" d="m92.443 76.162c0 19.038 8.897 35.378 23.577 42.828-6.17 12.34-14.02 23.22-22.214 31.41-14.858-17.96-28.29-41.92-33.802-88.686v-2.398h-21.921v2.4c10.128 77.884 40.308 102.68 48.288 107.44 4.516 2.7 8.402 2.58 12.53 0.25 6.479-3.68 25.939-23.13 36.719-45.92 4.53-0.01 9.96-0.53 15.38-1.75v-15.34c-3.32 0.77-6.53 1.1-9.42 1.1-16.25 0-28.76-11.35-28.76-31.084 0-9.673 3.74-14.703 9.03-14.703 5.03 0 8.38 4.514 8.38 13.672 0 4.552 0.42 10.225-2.42 11.889v2.4s5.01 8.736 18.7 6.055c2.91-6.455 4.49-14.816 4.49-22.149v-2.4c-0.77-18.311-10.8-28.813-28.51-28.813-18.34 0-29.356 13.096-30.047 31.393v2.4z"/>
 <path fill="#fff" d="m151 104c-3.32 0.77-6.52 1.1-9.41 1.1-16.25 0-28.77-11.345-28.77-31.08 0-9.672 3.74-14.702 9.03-14.702 5.03 0 8.39 4.512 8.39 13.671 0 5.207-1.4 10.913-2.43 14.289 0 0 5.01 8.736 18.7 6.055 2.91-6.455 4.49-14.815 4.49-22.149 0-19.734-10.06-31.214-28.5-31.214-18.96 0-30.053 14.576-30.053 33.794 0 19.038 8.903 35.376 23.573 42.826-6.17 12.34-14.02 23.22-22.209 31.41-14.86-17.96-28.292-41.92-33.804-88.682h-21.92c10.128 77.882 40.308 102.67 48.288 107.43 4.516 2.72 8.4 2.58 12.528 0.26 6.477-3.68 25.937-23.13 36.717-45.92 4.53-0.01 9.97-0.53 15.38-1.75v-15.34z"/>
</svg>
```

**Comment by liZe** [comment]
Hi!

Thanks for the bug report! The bug should be now fixed, feedback is welcome!
