### ISSUE TITLE
Missing embededimages and text

### ISSUE THREAD

**Issue by theoryshaw** [Kozea/CairoSVG#418]
Is it possible to convert the following files into a pdf?  They were created with https://blenderbim.org/
I couldn't get embed pngs to work, and text doesn't show up. 

svg: https://github.com/Kozea/CairoSVG/assets/507113/a9d54c99-9ae3-4c2a-8f50-63faae67f8dc
png referenced into svg: https://github.com/Kozea/CairoSVG/assets/507113/2b7a7c31-8b43-4431-8c1d-bfaf18439d90)

Here's the output....
![image](https://github.com/Kozea/CairoSVG/assets/507113/02148eb6-fe05-4f09-b346-129260a2b1e2)

What it should look like: 
![image](https://github.com/Kozea/CairoSVG/assets/507113/527fbb0e-b89f-4b87-9706-7c1db92399c7)

**Comment by liZe** [comment]
Hello!

Here’s the PDF I get

[out.pdf](https://github.com/Kozea/CairoSVG/files/14636831/out.pdf)

This result is much better than yours!

The image size is wrong, but I get the same rendering with my browsers, that’s not a problem with CairoSVG.

**Comment by theoryshaw** [comment]
cool!, if i can ask, what was the command line you used?

**Comment by theoryshaw** [comment]
> The image size is wrong, but I get the same rendering with my browsers...

That's weird, just to be sure i downloaded the svg/png from this github issue, and it seems to render correctly in Chorme and Firefox...

https://github.com/Kozea/CairoSVG/assets/507113/cd51e13e-29e8-4454-9f15-c506dd6ad2f4

**Comment by liZe** [comment]
> cool!, if i can ask, what was the command line you used?

`cairosvg file.svg -o file.pdf -u`

I’ve just changed the name of the PNG image in the SVG file so that it can it on disk.

> That's weird, just to be sure i downloaded the svg/png from this github issue, and it seems to render correctly in Chorme and Firefox...

My bad, I don’t know what I’ve done with this image!

[out.pdf](https://github.com/Kozea/CairoSVG/files/14637103/out.pdf)

**Comment by theoryshaw** [comment]
Hmm, i ran that command and got the following error. 
It creates the pdf, but the pdf is empty. 

```

Ryan Schultz@DESKTOP-8GRDBJI MINGW64 ~/Desktop
$ cairosvg
usage: cairosvg [-h] [-v] [-f {eps,pdf,png,ps,svg}] [-d DPI] [-W WIDTH]
                [-H HEIGHT] [-s SCALE] [-b COLOR] [-n] [-i] [-u]
                [--output-width OUTPUT_WIDTH] [--output-height OUTPUT_HEIGHT]
                [-o OUTPUT]
                input
cairosvg: error: the following arguments are required: input

Ryan Schultz@DESKTOP-8GRDBJI MINGW64 ~/Desktop
$ cairosvg "FRAMING - 2ND FLOOR-underlay.svg" -o "testy3.pdf" -u
Traceback (most recent call last):
  File "C:\Python312\Lib\urllib\request.py", line 1506, in open_local_file
    stats = os.stat(localfile)
            ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\FRAMING - 2ND FLOOR-underlay.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\cairosvg.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\cairosvg\__main__.py", line 78, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 133, in convert
    instance = cls(
               ^^^^
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 225, in __init__
    self.draw(tree)
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 472, in draw
    self.draw(child)
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 404, in draw
    TAGS[node.tag](self, node)
  File "C:\Python312\Lib\site-packages\cairosvg\image.py", line 28, in image
    image_bytes = node.fetch_url(url, 'image/*')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\cairosvg\parser.py", line 243, in fetch_url
    return read_url(url, self.url_fetcher, resource_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\cairosvg\url.py", line 154, in read_url
    return url_fetcher(url, resource_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\cairosvg\url.py", line 84, in fetch
    return urlopen(Request(url, headers=HTTP_HEADERS)).read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 1484, in file_open
    return self.open_local_file(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 1523, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 2] The system cannot find the file specified: 'C:\\FRAMING - 2ND FLOOR-underlay.png'>

Ryan Schultz@DESKTOP-8GRDBJI MINGW64 ~/Desktop

```

**Comment by theoryshaw** [comment]
Thanks @liZe, 

I ran it again, using your suggested command line prompt.  I got the background image, but the text doesn't show up. 

![2024-03-18_09-30-50_Revutesty5_-_Bluebeam_Revu_x64Revu](https://github.com/Kozea/CairoSVG/assets/507113/379f9b79-44e7-40fa-996c-5557de1af312)


```
Ryan Schultz@DESKTOP-8GRDBJI MINGW64 /d/Dropbox/Gitea_OD/Highland_Haven/Open/Models_and_CAD/BlenderBIM/drawings (main)
$ cairosvg "D:/Dropbox/Gitea_OD/Highland_Haven/Open/Models_and_CAD/BlenderBIM/drawings/test.svg" -o "D:/Dropbox/Gitea_OD/Highland_Haven/Open/Models_and_CAD/BlenderBIM/drawings/testy5.pdf" -u
_cairo_win32_scaled_font_set_metrics:GetTextMetrics: The operation completed successfully.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\cairosvg.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\cairosvg\__main__.py", line 78, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 133, in convert
    instance = cls(
               ^^^^
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 225, in __init__
    self.draw(tree)
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 472, in draw
    self.draw(child)
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 404, in draw
    TAGS[node.tag](self, node)
  File "C:\Python312\Lib\site-packages\cairosvg\text.py", line 69, in text
    surface.context.font_extents())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\cairocffi\context.py", line 1927, in font_extents
    self._check_status()
  File "C:\Python312\Lib\site-packages\cairocffi\context.py", line 107, in _check_status
    _check_status(cairo.cairo_status(self._pointer))
  File "C:\Python312\Lib\site-packages\cairocffi\__init__.py", line 87, in _check_status
    raise exception(message, status)
cairocffi.CairoError: cairo returned CAIRO_STATUS_WIN32_GDI_ERROR: b'error occurred in the Windows Graphics Device Interface'
```

**Comment by liZe** [comment]
I suppose that it’s the same problem as #377. The bug is probably in Cairo: https://gitlab.freedesktop.org/cairo/cairo/-/issues/530

You can try to use another font and see if it works. I’ll be even easier if you can use a Linux computer.

If it doesn’t work, you can try to add a comment on Cairo’s issue and hope for an answer. 🤞🏽
