### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by anton128355** [Kozea/CairoSVG#423]
Hello, I catch the issue above while using cairosvg.svg2png(bytestring=value). Maybe issue is in the svg (I`ll attach the file). More detailed traceback:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/SVGtoPNG/svg2png.py", line 25, in convert_svg_to_png
    png_source = cairosvg.svg2png(bytestring=value, unsafe=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cairosvg/surface.py", line 133, in convert
    instance = cls(
               ^^^^
  File "/usr/local/lib/python3.12/site-packages/cairosvg/surface.py", line 225, in __init__
    self.draw(tree)
  File "/usr/local/lib/python3.12/site-packages/cairosvg/surface.py", line 472, in draw
    self.draw(child)
  File "/usr/local/lib/python3.12/site-packages/cairosvg/surface.py", line 472, in draw
    self.draw(child)
  File "/usr/local/lib/python3.12/site-packages/cairosvg/surface.py", line 472, in draw
    self.draw(child)
  File "/usr/local/lib/python3.12/site-packages/cairosvg/surface.py", line 313, in draw
    transform(
  File "/usr/local/lib/python3.12/site-packages/cairosvg/helpers.py", line 249, in transform
    values = [size(surface, value) for value in transformation.split(' ')]
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cairosvg/helpers.py", line 388, in size
    number = float(string[:-len(unit)])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
```
![image](https://github.com/Kozea/CairoSVG/assets/47576921/a1e09497-5f9c-4c11-b5cf-d7645da35314)

**Comment by liZe** [comment]
Hi!

Thanks for this report. This is caused by `transform="translate(0,px)"`, which is invalid SVG.

CairoSVG focuses on valid SVG files and is really bad at handling SVG errors, by design. If you can’t or don’t want to fix your SVG files, you should use another fault-tolerant library such as rsvg or resvg.
