### ISSUE TITLE
Exception converting SVG to PNG

### ISSUE THREAD

**Issue by lkirkwood** [Kozea/CairoSVG#432]
I am using `svg2png` for the second leg of a `EMF -> SVG -> PNG` conversion. Certain images are throwing the following exception:

`Matrix.translate() takes 3 positional arguments but 4 were given`

Any thoughts? Can I enable more verbose logging in some way?

+ OS: Debian Bookworm
+ Python: 3.11.2
+ CairoSVG: 2.7.1

**Comment by liZe** [comment]
Hi!

Thanks for the report.

Could you please paste the whole backtrace? I suspect that the bug is [here](https://github.com/Kozea/CairoSVG/blob/main/cairosvg/helpers.py#L267), but I’d like to be sure.

**Comment by lkirkwood** [comment]
Looks like you were correct.

```
Traceback (most recent call last):
  File "/home/lkirkwood/projects/docs-toolkit/docs_toolkit/tasks/imgop.py", line 124, in convert_images
    convert_emf(path, outpath)
  File "/home/lkirkwood/projects/docs-toolkit/docs_toolkit/tasks/imgop.py", line 48, in convert_emf
    convert_svg(tempfile.name, outpath)
  File "/home/lkirkwood/projects/docs-toolkit/docs_toolkit/tasks/imgop.py", line 54, in convert_svg
    svg2png(url=inpath, write_to=outpath)
  File "/home/lkirkwood/.cache/pypoetry/virtualenvs/docs-toolkit-hu2R20-v-py3.10/lib/python3.10/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/home/lkirkwood/.cache/pypoetry/virtualenvs/docs-toolkit-hu2R20-v-py3.10/lib/python3.10/site-packages/cairosvg/surface.py", line 133, in convert
    instance = cls(
  File "/home/lkirkwood/.cache/pypoetry/virtualenvs/docs-toolkit-hu2R20-v-py3.10/lib/python3.10/site-packages/cairosvg/surface.py", line 225, in __init__
    self.draw(tree)
  File "/home/lkirkwood/.cache/pypoetry/virtualenvs/docs-toolkit-hu2R20-v-py3.10/lib/python3.10/site-packages/cairosvg/surface.py", line 472, in draw
    self.draw(child)
  File "/home/lkirkwood/.cache/pypoetry/virtualenvs/docs-toolkit-hu2R20-v-py3.10/lib/python3.10/site-packages/cairosvg/surface.py", line 313, in draw
    transform(
  File "/home/lkirkwood/.cache/pypoetry/virtualenvs/docs-toolkit-hu2R20-v-py3.10/lib/python3.10/site-packages/cairosvg/helpers.py", line 267, in transform
    matrix.translate(*values)
TypeError: Matrix.translate() takes 3 positional arguments but 4 were given
```
