### ISSUE TITLE
Denied image requests

### ISSUE THREAD

**Issue by rymohr** [Kozea/CairoSVG#68]
Just ran into an error where cloudfare denied a request for an image when trying to convert from an svg to a pdf.  I'm using `1.0.13`. Here's a reduced test case:

```
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="300" height="300" version="1.1">
  <image x="0" y="0" width="208" height="156"
         xlink:href="http://www.survivingcollege.com/wp-content/uploads/2013/03/Stanford-Tree-Logo-Mascot-Monday.jpg">
  </image>
</svg>
```

```
cairosvg test.svg test.pdf

Traceback (most recent call last):
  File "/usr/local/bin/cairosvg", line 25, in <module>
    cairosvg.main()
  File "/Library/Python/2.7/site-packages/cairosvg/__init__.py", line 93, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/Library/Python/2.7/site-packages/cairosvg/surface/__init__.py", line 87, in convert
    cls(tree, output, dpi).finish()
  File "/Library/Python/2.7/site-packages/cairosvg/surface/__init__.py", line 141, in __init__
    self.draw_root(tree)
  File "/Library/Python/2.7/site-packages/cairosvg/surface/__init__.py", line 394, in draw_root
    self.draw(node)
  File "/Library/Python/2.7/site-packages/cairosvg/surface/__init__.py", line 350, in draw
    self.draw(child)
  File "/Library/Python/2.7/site-packages/cairosvg/surface/__init__.py", line 303, in draw
    TAGS[node.tag](self, node)
  File "/Library/Python/2.7/site-packages/cairosvg/surface/image.py", line 119, in image
    url=url, bytestring=image_bytes, tree_cache=surface.tree_cache)
  File "/Library/Python/2.7/site-packages/cairosvg/parser.py", line 270, in __init__
    tree = ElementTree.fromstring(bytestring)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: undefined entity: line 29, column 65

%PDF-1.5
%????
3 0 obj
<< /Length 4 0 R
   /Filter /FlateDecode
>>
stream
x?+?
???
endstream
endobj
4 0 obj
   12
endobj
2 0 obj
<<
>>
endobj
5 0 obj
<< /Type /Page
   /Parent 1 0 R
   /MediaBox [ 0 0 225 225 ]
   /Contents 3 0 R
   /Group <<
      /Type /Group
      /S /Transparency
      /I true
      /CS /DeviceRGB
   >>
   /Resources 2 0 R
>>
endobj
1 0 obj
<< /Type /Pages
   /Kids [ 5 0 R ]
   /Count 1
>>
endobj
6 0 obj
<< /Creator (cairo 1.12.16 (http://cairographics.org))
   /Producer (cairo 1.12.16 (http://cairographics.org))
>>
endobj
7 0 obj
<< /Type /Catalog
   /Pages 1 0 R
>>
endobj
xref
0 8
0000000000 65535 f 
0000000360 00000 n 
0000000125 00000 n 
0000000015 00000 n 
0000000104 00000 n 
0000000146 00000 n 
0000000425 00000 n 
0000000554 00000 n 
trailer
<< /Size 8
   /Root 7 0 R
   /Info 6 0 R
>>
startxref
606
%%EOF
```

The same file works fine using wkhtmltopdf

```
wkhtmltopdf test.svg test.pdf
```

Any ideas why cloudfare would permit the request from wkhtmltopdf and deny it for cairo?

**Comment by SimonSapin** [comment]
I’d bet on the `User-Agent` HTTP header. Wikimedia used to deny serving images to WeasyPrint before we gave it a non-default User-Agent string.

**Comment by rymohr** [comment]
I think you're right.  What user-agent string did you end up going with for WeasyPrint?

**Comment by SimonSapin** [comment]
It’s [`'WeasyPrint %s (http://weasyprint.org/)' % VERSION`](https://github.com/Kozea/WeasyPrint/blob/492619662f93f37b7a91288d86215a90b90bb534/weasyprint/__init__.py#L23) (see [`urls.py`](https://github.com/Kozea/WeasyPrint/blob/492619662f93f37b7a91288d86215a90b90bb534/weasyprint/urls.py#L276)), but I think anything that doesn’t mention "urllib" should be fine.
