### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by misbach** [Kozea/CairoSVG#7]
I'm trying to convert an svg to a pdf using cairosvg v0.4.3. The svg converts fine with inkscape or illustrator. Can anyone tell me if I'm doing something wrong, or what's wrong with my svg file?

You can download the chart.svg file I'm using from here:
https://www.box.com/s/o3qo6w1k45889fom7yq8

Here is the command line I'm using:
cairosvg chart.svg -o chart.pdf

I'm getting the following stack trace:
Traceback (most recent call last):
  File "./cairosvg", line 25, in <module>
    cairosvg.main()
  File "/usr/lib/python3/dist-packages/cairosvg/**init**.py", line 92, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 78, in convert
    cls(tree, output, dpi).finish()
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 119, in **init**
    self.draw_root(tree)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 312, in draw_root
    self.draw(node)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 277, in draw
    self.draw(child, stroke_and_fill)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 277, in draw
    self.draw(child, stroke_and_fill)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 277, in draw
    self.draw(child, stroke_and_fill)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/**init**.py", line 236, in draw
    TAGS[node.tag](self, node)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/path.py", line 302, in path
    draw_marker(surface, node, "end")
  File "/usr/lib/python3/dist-packages/cairosvg/surface/defs.py", line 167, in draw_marker
    angle1 = node.tangents.pop(0)
IndexError: pop from empty list

**Comment by pvolyntsev** [comment]
The save with cairosvg v1.0.9 on Ubuntu.

    $ cairosvg --version
    1.0.9
    $ python --version
    Python 2.7.3
    $ cat /etc/debian_version
    wheezy/sid

svg sample is here https://www.dropbox.com/s/agcq2jfam5mz146/file.svg?dl=0

command to convert

    cairosvg file.svg -o file.pdf

error and stacktrace

    Traceback (most recent call last):
    File "/usr/local/bin/cairosvg", line 25, in <module>
      cairosvg.main()
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/__init__.py", line 92, in main
      SURFACES[output_format.upper()].convert(**kwargs)
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/__init__.py", line 87, in convert
      cls(tree, output, dpi).finish()
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/__init__.py", line 141, in __init__
      self.draw_root(tree)
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/__init__.py", line 394, in draw_root
      self.draw(node)
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/__init__.py", line 350, in draw
      self.draw(child)
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/__init__.py", line 350, in draw
      self.draw(child)
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/__init__.py", line 303, in draw
      TAGS[node.tag](self, node)
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/path.py", line 324, in path
      draw_marker(surface, node, "end")
    File "/usr/local/lib/python2.7/dist-packages/cairosvg/surface/defs.py", line 279, in draw_marker
      angle1 = node.tangents.pop(0)
    IndexError: pop from empty list

**Comment by liZe** [comment]
That was another problem with the same stacktrace, fixed in 1.0.12.
