### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by ryanpineo** [Kozea/CairoSVG#86]
While trying to convert an svg to a png i'm getting this exception, `ZeroDivisionError: float divison by zero`.  I've been able to convert the SVG without issue using other services (http://www.grumpicon.com/). 

The SVG: http://assets.tve.synacor.edgesuite.net/assets/built/natgeowild.c68ce24aafa107825844ceb7a14ea1a3254fa0d8.svg

Stacktrace:

```
Traceback (most recent call last):
  File "/home/ryan/.venvs/venv/bin/cairosvg", line 25, in <module>
    cairosvg.main()
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/__init__.py", line 93, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 106, in convert
    cls(tree, output, dpi).finish()
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 160, in __init__
    self.draw_root(tree)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 213, in draw_root
    self.draw(node)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 391, in draw
    paint_mask(self, node, mask, opacity)
  File "/home/ryan/.venvs/venv/lib/python3.4/site-packages/cairosvg/surface/defs.py", line 155, in paint_mask
    mask_node["width"] / mask_surface.width or 1,
ZeroDivisionError: float division by zero
```

I believe the problem is somewhere in the letter "D" in the word "wild".  Not sure what could be causing it though.

**Comment by ryanpineo** [comment]
Awesome! Thank you so much

On Sat, Feb 20, 2016 at 10:56 a.m., Guillaume Ayoub < notifications@github.com [notifications@github.com] > wrote:
Closed #86 [https://github.com/Kozea/CairoSVG/issues/86] via b73b3f1
[https://github.com/Kozea/CairoSVG/commit/b73b3f1a98382038b573151985a77d40ef13c531] .

**Comment by liZe** [comment]
:)

**Comment by chutchut** [comment]
https://github.com/Kozea/CairoSVG/blob/1.0.22/cairosvg/surface/defs.py#L131-L134

This issue still exists in version 1.0.22 (the last supported version for Python 2.7 afaik..?), could you please back-port the fix to this version? Thanks
