### ISSUE TITLE
Float division by Zero (probably with a mask)

### ISSUE THREAD

**Issue by lukesneeringer** [Kozea/CairoSVG#96]
I am trying to convert the following SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="1287.7263581488935" viewBox="528 25 497 800" width="800" data-reactroot="" data-reactid="1" data-react-checksum="448288273">
    <svg height="850" viewBox="0 0 1050 850" width="1050" data-reactid="2">
        <image width="1050" height="850" x="0" y="0" xlink:href="http://md-pattern-cache.global.ssl.fastly.net/britt-bass-fruitie/full/" data-reactid="3"></image>
    </svg>
    <svg height="224.95" width="224.95" viewBox="0 0 224.95 224.95" x="668.775" y="117.52499999999998" data-reactid="4">
        <g data-reactid="5">
            <svg viewBox="0 0 160 160" width="224.95" height="224.95">
                <circle fill="#FFFFFF" cx="80" cy="80" r="80" />
                <circle fill="none" stroke="#57d2c8" stroke-width="1.1" cx="80" cy="80" r="72" />
            </svg>
        </g>
        <svg data-reactid="6">
            <defs data-reactid="7">
                <mask id="logo-mask" data-reactid="8">
                    <image xlink:href="https://md-iris-assets.global.ssl.fastly.net/test-logos/twelve-stone-white.png" x="39.366249999999994" y="58.487" width="146.2175" height="107.97599999999998" data-reactid="9"></image>
                </mask>
            </defs>
            <rect x="39.366249999999994" y="58.487" width="146.2175" height="107.97599999999998" fill="#57d2c8" mask="url(#logo-mask)" data-reactid="10"></rect>
        </svg>
    </svg>
</svg>
```

I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/cairosvg", line 25, in <module>
    cairosvg.main()
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/__init__.py", line 101, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/__init__.py", line 108, in convert
    cls(tree, output, dpi, None, parent_width, parent_height).finish()
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/__init__.py", line 161, in __init__
    self.draw_root(tree)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/__init__.py", line 214, in draw_root
    self.draw(node)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/__init__.py", line 385, in draw
    self.draw(child)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/__init__.py", line 328, in draw
    TAGS[node.tag](self, node)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/svg.py", line 44, in svg
    preserve_ratio(surface, node)
  File "/usr/local/lib/python3.4/dist-packages/cairosvg/surface/helpers.py", line 135, in preserve_ratio
    scale_x = width / node.image_width
ZeroDivisionError: float division by zero
```

**Comment by liZe** [comment]
I get the error with version 1.x, but not with the 2.0.0rc1 (current git version). I think that it's already fixed!
